Repository pralinkhaira1903/HacktoberFest2k23, pull requests merged in 2023-10, with the labels that each got.

#19 Make program to check odd or even number
  Code/Java/EvenOddChecker.java
Labels: hacktober-fest-accepted

#18 added myself and java code
  Code/Java/Int2Binary.java
  Contributers.md
Labels: hacktober-fest-accepted

#26 Fixed Games Directory.
  Games/Tic Tac Toe/Gui.PNG
  Games/Tic Tac Toe/README.md
  Games/Tic Tac Toe/Tic_Tac_Toe_Game.py
  Games/Tic Tac Toe/Winning_message.PNG
  Games/Tic Tac Toe/draw_messge.PNG
Labels: hacktober-fest-accepted

#24 Create Check_whether_number_is_whole_or_not
  Code/Python/Check_whether_number_is_whole_or_not.py
Labels: hacktober-fest-accepted

#16 Create ValidParenthesis-Prayatharth
  Code/C++/ValidParenthesis-Prayatharth.cpp
Labels: hacktober-fest-accepted

#11 Sorting Algorithms in cpp
  Code/C++/Sorting Algorithms/SelectionSort.cpp
Labels: hacktober-fest-accepted

#29 Update Contributers.md
  Contributers.md
Labels: Update/Correction-Needed

#30 Create
  Code/Python/Boruvka-s_Algorithm-MMVonnSeek.py
  Contributers.md
Labels: documentation, Update/Correction-Needed, Repo-Not-Starred

#32 Add binary search to code in python
  Code/Python/Binary_search.py
  Contributers.md
Labels: documentation, Update/Correction-Needed, Repo-Not-Starred

#37 Add new game
  Games/Pong/PongGame-By-Virej.py
Labels: documentation, question

#39 Added QuickSort Algorithms in CPP Folder
  Code/C++/Sorting Algorithms/QuickSort.cpp
Labels: hacktoberfest-accepted
